apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
    version: v1
    app.kubernetes.io/part-of: app1-application
  name: forumapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
      version: v1
  template:
    metadata:
      labels:
        app: app1
        version: v1
    spec:
      containers:
      - env:
        image: quay.io/ilawson/forum2020httpd:latest
        imagePullPolicy: Always
        name: app1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
          - name: APPNAME
            value: forumapp1
          - name: VERSION
            value: v1
