apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: forumapp1placement
  namespace: forumapp1
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      type: app
