apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: forumapp1subscription
  namespace: forumapp1
  labels:
    app: app1
  annotations:
    apps.open-cluster-management.io/github-path: application
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: forumapp1/forumapp1channel
  placement:
    placementRef:
      kind: PlacementRule
      name: forumapp1placement
